fix a typo in external-representations.md
BrickSchema/docs pull request #17
Opened 2023-08-20 21:30 UTC by Reapor-Yurnero

2023-08-20 21:54 UTC, gtfierro requested changes
I think it should actually be `ref:hasExternalReference`, no?

2023-08-20 22:24 UTC, Reapor-Yurnero commented
Either way works if I'm understanding correctly. ref:hasTimeseriesReference
should be a subProperty of ref:hasExternalReference
Best regards,
Xiaohan Fu


On Sun, Aug 20, 2023 at 2:55 PM Gabe Fierro ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I think it should actually be ref:hasExternalReference, no?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BrickSchema/docs/pull/17#pullrequestreview-1585966048>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADVJW23A5OTDYVSF23JUWH3XWKBT5ANCNFSM6AAAAAA3XQ3P4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-20 22:25 UTC, gtfierro commented
The prefix still needs to be fixed in your PR. Either property is fine



--

Dr. Gabe Fierro | https://home.gtf.fyi<https://home.gtf.fyi/>

Assistant Professor of Computer Science | Colorado School of Mines

Joint Appointment | National Renewable Energy Laboratory

________________________________
From: Xiaohan Fu ***@***.***>
Sent: Sunday, August 20, 2023 4:24:46 PM
To: BrickSchema/docs ***@***.***>
Cc: Gabe Fierro ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [BrickSchema/docs] fix a typo in external-representations.md (PR #17)

CAUTION: This email originated from outside of the Colorado School of Mines organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.


Either way works if I'm understanding correctly. ref:hasTimeseriesReference
should be a subProperty of ref:hasExternalReference
Best regards,
Xiaohan Fu


On Sun, Aug 20, 2023 at 2:55 PM Gabe Fierro ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I think it should actually be ref:hasExternalReference, no?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BrickSchema/docs/pull/17#pullrequestreview-1585966048>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADVJW23A5OTDYVSF23JUWH3XWKBT5ANCNFSM6AAAAAA3XQ3P4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

—
Reply to this email directly, view it on GitHub<https://github.com/BrickSchema/docs/pull/17#issuecomment-1685411847>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAANRCSFFAR4CZOQUPTI3VDXWKFC5ANCNFSM6AAAAAA3XQ3P4Y>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-08-20 22:28 UTC, Reapor-Yurnero commented
oops. fixed the typo in the fix lol

2023-08-20 22:43 UTC, Reapor-Yurnero commented
okay i notice the example query below is against ExternalReference with no subref propagation so I just made it externalReference

2023-08-21 05:07 UTC, gtfierro approved these changes

2023-08-21 05:07 UTC, merged